import { z } from "zod";

const id = z.string().min(1).max(256);
const app = z.enum(["photoshop", "illustrator", "after-effects", "premiere-pro"]);
const risk = z.enum(["R0", "R1", "R2", "R3", "R4"]);
const target = z.object({ app, instanceId: id.optional(), projectId: id.optional(), documentId: id.optional(), entityId: id.optional() }).strict();
const operationId = z.string().uuid();
const mutationOptions = z.object({ operationId, expectedRevision: id.optional(), dryRun: z.boolean().default(false), atomic: z.boolean().default(true), conflictPolicy: z.enum(["fail", "rebase-safe"]).default("fail"), verification: z.enum(["none", "state", "render-proof"]).default("state"), approvalToken: z.string().min(1).max(4096).optional(), explicitConfirmation: z.boolean().optional() }).strict();
const fileGrant = z.object({ grantId: id, access: z.enum(["read", "write", "read-write"]), suggestedName: z.string().max(255).optional() }).strict();

export const ToolCategory = z.enum(["color", "timeline", "selection", "shapes", "export", "typography", "media", "render", "project", "layer", "channel", "expression"]);
export const VerificationLevel = z.enum(["implemented", "host_verified", "experimental", "unavailable"]);
export const ToolApp = app;
export const ToolDiscoveryInput = z.object({ app: app.optional(), category: ToolCategory.optional(), risk: risk.optional(), query: z.string().max(256).optional(), verification: VerificationLevel.optional(), includeUnavailable: z.boolean().default(false), cursor: z.string().max(2048).optional(), limit: z.number().int().min(1).max(200).default(50) }).strict();
export const ToolCatalogEntry = z.object({ name: id, description: z.string().max(2048), app: app.optional(), categories: z.array(ToolCategory).max(8), risk, mutating: z.boolean(), verification: VerificationLevel, requiredCapabilities: z.array(z.string().max(128)).max(32) }).strict();
export const ToolDiscoveryResult = z.object({ tools: z.array(ToolCatalogEntry).max(200), nextCursor: z.string().max(2048).optional(), total: z.number().int().nonnegative() }).strict();
export const ToolDescribeInput = z.object({ name: id }).strict();
export const ToolExample = z.object({ title: z.string().max(256), input: z.record(z.string(), z.unknown()), expected: z.record(z.string(), z.unknown()).optional() }).strict();
export const ToolDescribeResult = z.object({ tool: ToolCatalogEntry, inputSchema: z.record(z.string(), z.unknown()), outputSchema: z.record(z.string(), z.unknown()), examples: z.array(ToolExample).max(20), limitations: z.array(z.string().max(1024)).max(20), verifiedAt: z.string().datetime().optional() }).strict();

export const PlanSnapshot = z.object({ snapshotId: id, revision: id, sha256: z.string().regex(/^[a-f0-9]{64}$/), artifactUri: z.string().regex(/^artifact:\/\/sha256-[a-f0-9]{64}$/), verified: z.boolean() }).strict();
export const PlanPreview = z.object({ summary: z.string().max(2048), diff: z.array(z.object({ op: z.enum(["create", "set", "transform", "delete", "export", "invoke"]), entityId: id.optional(), before: z.unknown().optional(), after: z.unknown().optional() }).strict()).max(500), estimated: z.object({ entities: z.number().int().nonnegative(), files: z.number().int().nonnegative(), bytes: z.number().int().nonnegative(), minutes: z.number().nonnegative() }).strict(), warnings: z.array(z.string().max(1024)).max(50) }).strict();
export const PlanHandle = z.object({ planId: id, planHash: z.string().regex(/^[a-f0-9]{64}$/), target, toolName: id, risk, scope: z.object({ entities: z.number().int().nonnegative(), files: z.number().int().nonnegative(), bytes: z.number().int().nonnegative(), minutes: z.number().nonnegative() }).strict(), expectedRevisions: z.record(id, id), expiresAt: z.string().datetime(), commandsDigest: z.string().regex(/^[a-f0-9]{64}$/), commands: z.array(z.record(z.string(), z.unknown())).min(1).max(500), snapshot: PlanSnapshot, preview: PlanPreview, immutable: z.literal(true) }).strict();
export const OperationsPlanInput = z.object({ target, toolName: id, commands: z.array(z.record(z.string(), z.unknown())).min(1).max(500), options: mutationOptions }).strict();
export const OperationsExecuteInput = z.preprocess((value) => { if (value && typeof value === "object" && "planHandle" in value && !("plan" in value)) return { ...(value as Record<string, unknown>), plan: (value as Record<string, unknown>).planHandle }; return value; }, z.object({ planHandle: PlanHandle, approval: z.unknown().optional(), plan: z.unknown().optional(), options: mutationOptions }).strict().superRefine((v, c) => { if (!v.approval && !v.options.approvalToken) c.addIssue({ code: "custom", path: ["approval"], message: "approval token is required to execute a PlanHandle" }); }));
export const OperationsExecuteResult = z.object({ operationId, planHash: z.string().regex(/^[a-f0-9]{64}$/), status: z.enum(["planned", "applied", "verified"]), receipt: z.record(z.string(), z.unknown()), verification: z.object({ ok: z.boolean(), revision: id }).strict() }).strict();

const color = z.object({ space: z.enum(["rgb", "cmyk", "lab", "gray"]), components: z.array(z.number().min(0).max(1)).min(1).max(4), alpha: z.number().min(0).max(1).default(1) }).strict();
export const PhotoshopSmartSelection = z.object({ target: target.refine((v) => v.app === "photoshop"), mode: z.enum(["selectSubject", "colorRange", "objectSelection"]), colorRange: z.object({ color: color, fuzziness: z.number().min(0).max(200).default(40), hue: z.number().min(0).max(360).optional() }).strict().optional(), boundingBox: z.object({ x: z.number().finite(), y: z.number().finite(), width: z.number().positive(), height: z.number().positive(), unit: z.enum(["px", "pt", "percent"]).default("px") }).strict().optional(), options: mutationOptions }).strict().superRefine((v, c) => { if (v.mode === "colorRange" && !v.colorRange) c.addIssue({ code: "custom", path: ["colorRange"], message: "colorRange is required" }); if (v.mode === "objectSelection" && !v.boundingBox) c.addIssue({ code: "custom", path: ["boundingBox"], message: "boundingBox is required" }); });
export const PhotoshopLayerStyle = z.object({ target: target.refine((v) => v.app === "photoshop"), layerId: id, style: z.enum(["dropShadow", "stroke", "bevelEmboss", "innerGlow", "outerGlow", "colorOverlay", "gradientFill"]), enabled: z.boolean().default(true), opacity: z.number().min(0).max(100).optional(), angle: z.number().finite().optional(), size: z.number().nonnegative().optional(), spread: z.number().nonnegative().max(100).optional(), color: color.optional(), gradient: z.array(color).min(2).max(32).optional(), options: mutationOptions }).strict();
export const PhotoshopChannelMask = z.object({ target: target.refine((v) => v.app === "photoshop"), layerId: id.optional(), source: z.enum(["lights", "midtones", "shadows", "alpha"]), channelId: id.optional(), invert: z.boolean().default(false), featherPixels: z.number().nonnegative().max(10000).default(0), options: mutationOptions }).strict().superRefine((v, c) => { if (v.source === "alpha" && !v.channelId) c.addIssue({ code: "custom", path: ["channelId"], message: "channelId is required for alpha masks" }); });
export const PhotoshopLayerExportAdvanced = z.object({ target: target.refine((v) => v.app === "photoshop"), layerIds: z.array(id).max(10000).optional(), groupIds: z.array(id).max(1000).optional(), format: z.enum(["png", "psd"]), scale: z.number().positive().max(16).default(1), includeHidden: z.boolean().default(false), isolate: z.boolean().default(true), destination: fileGrant, options: mutationOptions, planHandle: z.unknown().optional(), approval: z.unknown().optional(), plan: z.unknown().optional() }).strict();
export const PhotoshopLayerExportAdvancedResult = z.object({ manifestUri: z.string().regex(/^artifact:\/\/sha256-[a-f0-9]{64}$/), artifacts: z.array(z.object({ layerId: id, name: id, uri: z.string().regex(/^artifact:\/\/sha256-[a-f0-9]{64}$/), sha256: z.string().regex(/^[a-f0-9]{64}$/), mediaType: z.string(), width: z.number().int().positive().optional(), height: z.number().int().positive().optional() }).strict()).max(10000) }).strict();

export const PremiereMogrtParametrize = z.object({ target: target.refine((v) => v.app === "premiere-pro"), clipId: id, templateFingerprint: id, parameters: z.array(z.object({ key: id, type: z.enum(["text", "color", "number", "boolean", "media"]), value: z.unknown(), mediaArtifactUri: z.string().regex(/^artifact:\/\/sha256-[a-f0-9]{64}$/).optional() }).strict()).min(1).max(500), options: mutationOptions }).strict();
export const PremiereLumetriGrade = z.object({ target: target.refine((v) => v.app === "premiere-pro"), clipIds: z.array(id).min(1).max(500), basic: z.object({ exposure: z.number().min(-10).max(10).optional(), contrast: z.number().min(-100).max(100).optional(), whites: z.number().min(-100).max(100).optional(), blacks: z.number().min(-100).max(100).optional(), temperature: z.number().min(-100).max(100).optional(), tint: z.number().min(-100).max(100).optional() }).strict().optional(), wheels: z.object({ shadows: color.optional(), midtones: color.optional(), highlights: color.optional() }).strict().optional(), curves: z.object({ rgb: z.array(z.tuple([z.number().min(0).max(1), z.number().min(0).max(1)])).max(256).optional(), hueVsSaturation: z.array(z.tuple([z.number().min(0).max(1), z.number().min(0).max(1)])).max(256).optional() }).strict().optional(), lut: z.object({ uri: z.string().regex(/^artifact:\/\/sha256-[a-f0-9]{64}$/).or(z.string().min(1).max(4096)), format: z.enum(["cube", "look"]), intensity: z.number().min(0).max(1).default(1) }).strict().optional(), options: mutationOptions }).strict();
export const PremiereProjectOrganize = z.object({ target: target.refine((v) => v.app === "premiere-pro"), createBins: z.array(z.object({ id: id.optional(), name: id, parentId: id.optional() }).strict()).max(1000).default([]), imports: z.array(z.object({ source: z.string().min(1).max(4096).or(z.string().regex(/^artifact:\/\/sha256-[a-f0-9]{64}$/)), binId: id.optional(), labelColor: z.enum(["none", "red", "orange", "yellow", "green", "blue", "purple", "pink"]).default("none") }).strict()).max(1000).default([]), options: mutationOptions }).strict();

export const AfterEffectsShapeCreate = z.object({ target: target.refine((v) => v.app === "after-effects"), compId: id, groupName: id, shapes: z.array(z.object({ type: z.enum(["rectangle", "ellipse", "path", "polystar"]), vertices: z.array(z.tuple([z.number().finite(), z.number().finite()])).max(10000).optional(), size: z.tuple([z.number().positive(), z.number().positive()]).optional() }).strict()).min(1).max(500), modifiers: z.object({ trimPaths: z.object({ start: z.number().min(0).max(100), end: z.number().min(0).max(100), offset: z.number().finite().default(0) }).strict().optional(), repeater: z.object({ copies: z.number().int().min(1).max(1000), offset: z.tuple([z.number().finite(), z.number().finite()]), scale: z.number().positive().max(100).default(1) }).strict().optional(), puckerAndBloat: z.object({ amount: z.number().min(-100).max(100) }).strict().optional() }).strict().default({}), options: mutationOptions }).strict();
export const AfterEffectsTextAnimate = z.object({ target: target.refine((v) => v.app === "after-effects"), layerId: id, text: z.string().max(100000).optional(), properties: z.object({ position: z.boolean().optional(), scale: z.boolean().optional(), rotation: z.boolean().optional(), opacity: z.boolean().optional(), tracking: z.boolean().optional() }).strict(), rangeSelector: z.object({ start: z.number().min(0).max(100), end: z.number().min(0).max(100), offset: z.number().min(-100).max(100), smoothness: z.number().min(0).max(100).default(100) }).strict(), wiggle: z.object({ frequency: z.number().nonnegative().max(100), amplitude: z.number().finite().max(10000) }).strict().optional(), options: mutationOptions }).strict();
export const AfterEffectsExpressionControl = z.object({ target: target.refine((v) => v.app === "after-effects"), layerId: id, control: z.enum(["slider", "color", "point", "angle"]), name: id, value: z.number().finite().or(z.array(z.number().finite()).min(2).max(4)), expression: z.string().max(10000).optional(), options: mutationOptions }).strict();
export const AfterEffectsRenderAdvanced = z.object({ projectPath: z.string().min(1).max(4096), comp: id.optional(), outputPath: z.string().min(1).max(4096), startFrame: z.number().int().nonnegative().optional(), endFrame: z.number().int().nonnegative().optional(), segmentSize: z.number().int().positive().max(100000).optional(), renderSettingsTemplate: z.string().max(256).optional(), outputModuleTemplate: z.string().max(256).optional(), options: mutationOptions, planHandle: z.unknown().optional(), approval: z.unknown().optional(), plan: z.unknown().optional() }).strict().superRefine((v, c) => { if (v.endFrame !== undefined && v.startFrame !== undefined && v.endFrame < v.startFrame) c.addIssue({ code: "custom", path: ["endFrame"], message: "endFrame must be >= startFrame" }); });

export const IllustratorImageTrace = z.object({ target: target.refine((v) => v.app === "illustrator"), imageId: id, preset: z.enum(["logo", "silhouette", "sketch", "highFidelityPhoto"]), threshold: z.number().min(0).max(255).optional(), colors: z.number().int().min(2).max(256).optional(), options: mutationOptions }).strict();
export const IllustratorSwatchesCreate = z.object({ target: target.refine((v) => v.app === "illustrator"), colors: z.array(z.object({ name: id, color: color, global: z.boolean().default(true) }).strict()).min(1).max(1000), harmony: z.enum(["none", "complementary", "analogous", "triadic", "split-complementary", "tetradic"]).default("none"), options: mutationOptions }).strict();
export const IllustratorVariableTypography = z.object({ target: target.refine((v) => v.app === "illustrator"), textItemId: id, fontFamily: id.optional(), axes: z.object({ weight: z.number().min(1).max(1000).optional(), width: z.number().min(1).max(1000).optional(), slant: z.number().min(-90).max(90).optional() }).strict(), options: mutationOptions }).strict();
export const PhotoshopTransformApply = z.object({ target: target.refine((v) => v.app === "photoshop"), layerId: id, mode: z.enum(["free", "perspective", "warp", "skew", "rotate"]), matrix: z.array(z.number().finite()).min(4).max(16).optional(), warpGrid: z.object({ columns: z.number().int().min(1).max(32), rows: z.number().int().min(1).max(32), points: z.array(z.tuple([z.number().finite(), z.number().finite()])).max(1024) }).strict().optional(), interpolation: z.enum(["bicubic", "nearestNeighbor", "bilinear", "bicubicSmoother", "bicubicSharper"]).default("bicubic"), options: mutationOptions }).strict();
export const PhotoshopGenerativeFill = z.object({ target: target.refine((v) => v.app === "photoshop"), layerId: id.optional(), prompt: z.string().min(1).max(2000), selectionMaskArtifactUri: z.string().regex(/^artifact:\/\/sha256-[a-f0-9]{64}$/).optional(), variationsCount: z.number().int().min(1).max(4).default(3), options: mutationOptions }).strict();

export const PremiereProxiesManage = z.object({ target: target.refine((v) => v.app === "premiere-pro"), clipIds: z.array(id).min(1).max(500), action: z.enum(["attach", "detach", "toggle", "status"]), proxyPaths: z.array(z.string().min(1).max(4096)).max(500).optional(), enableProxies: z.boolean().optional(), options: mutationOptions }).strict();
export const PremiereTranscriptSync = z.object({ target: target.refine((v) => v.app === "premiere-pro"), sequenceId: id, language: z.string().max(32).default("auto"), createCaptionsTrack: z.boolean().default(true), maxCharactersPerLine: z.number().int().min(10).max(100).default(37), options: mutationOptions }).strict();

export const AfterEffectsTrackingExtract = z.object({ target: target.refine((v) => v.app === "after-effects"), compId: id, layerId: id, trackerType: z.enum(["3dCameraTracker", "pointTracker", "mochaAE", "stabilizer"]), exportFormat: z.enum(["json", "nullRig", "cameraRig", "cornerPin"]), options: mutationOptions }).strict();

export const IllustratorSymbolsManage = z.object({ target: target.refine((v) => v.app === "illustrator"), action: z.enum(["create", "place", "redefine", "applyGraphicStyle"]), name: id, itemIds: z.array(id).max(1000).optional(), position: z.tuple([z.number().finite(), z.number().finite()]).optional(), styleName: id.optional(), options: mutationOptions }).strict();

export type PlanHandle = z.infer<typeof PlanHandle>;
export type ToolCatalogEntry = z.infer<typeof ToolCatalogEntry>;
export type ToolDiscoveryInput = z.infer<typeof ToolDiscoveryInput>;
export type ToolDescribeResult = z.infer<typeof ToolDescribeResult>;

