import { describe, expect, it } from "vitest";
import type { AppId } from "@adobe-mcp/schemas";
import { executionOrder, executeSaga, SagaTransactionLog, validateWorkflow } from "./index.js";
describe("workflow engine", () => { it("rejects cycles and orders dependencies", () => { expect(() => validateWorkflow({ version: "1", nodes: [{ id: "a", tool: "x", dependsOn: ["b"] }, { id: "b", tool: "x", dependsOn: ["a"] }] })).toThrow("cycle"); expect(executionOrder({ version: "1", nodes: [{ id: "b", tool: "x", dependsOn: ["a"] }, { id: "a", tool: "x" }] })).toEqual(["a", "b"]); }); });
describe("cross-app sagas", () => { it("compensates in reverse order and is idempotent", async () => { const calls: string[] = []; const log = new SagaTransactionLog(); const result = await executeSaga({ id: "saga", version: "1", steps: [{ id: "ps", app: "photoshop", tool: "export", input: {}, compensateTool: "undo", idempotencyKey: "tx:ps" }, { id: "ai", app: "illustrator", tool: "compose", input: {}, compensateTool: "undo", idempotencyKey: "tx:ai" }, { id: "ae", app: "after-effects", tool: "render", input: {}, compensateTool: "undo", idempotencyKey: "tx:ae" }] }, { async execute(_app, tool, _input, key) { calls.push(`do:${tool}:${key}`); if (tool === "render") throw new Error("failed"); return key; }, async compensate(_app, tool, _input, key) { calls.push(`undo:${tool}:${key}`); } }, "tx-1", log); expect(result.status).toBe("rolled-back"); expect(result.compensations).toEqual(["ai", "ps"]); expect(calls.slice(-2).map((entry) => entry.split(":")[0])).toEqual(["undo", "undo"]); }); });
describe("saga transaction isolation", () => { it("scopes identical step keys per transaction and preserves compensation errors", async () => {
  const log = new SagaTransactionLog(); const calls: string[] = []; const definition = { id: "saga", version: "1", steps: [{ id: "one", app: "photoshop" as const, tool: "do", input: {}, compensateTool: "undo", idempotencyKey: "same-step" }, { id: "two", app: "illustrator" as const, tool: "fail", input: {}, compensateTool: "undo", idempotencyKey: "other-step" }] };
  const executor = { async execute(_app: AppId, tool: string, _input: unknown, key: string) { calls.push(`execute:${key}`); if (tool === "fail") throw new Error("step failed"); return key; }, async compensate(_app: AppId, _tool: string, _input: unknown, key: string) { calls.push(`compensate:${key}`); throw new Error("compensation failed"); } };
  const first = await executeSaga(definition, executor, "tx-a", log); const second = await executeSaga(definition, executor, "tx-b", log);
  expect(first.compensationErrors).toHaveLength(1); expect(second.compensationErrors).toHaveLength(1); expect(calls.filter((call) => call.startsWith("execute:")).every((call) => call.includes("tx-a:") || call.includes("tx-b:"))).toBe(true);
}); });
