import { z } from "zod";
import { zodToJsonSchema } from "zod-to-json-schema";
import {
  AeCompState, AfterEffectsEditCommand, AfterEffectsPresetApply, AiDocumentState, ArtifactRef, AppId, ApprovalToken, FileGrant,
  IllustratorArtboardExport, IllustratorEditCommand, Job, MutationOptions, OperationReceipt, PsDocumentState, PhotoshopLayerCommand,
  PhotoshopLayerExportResult, PhotoshopLayerExportSpec, Plan, PreviewCaptureData, PreviewCaptureInput, PrSequenceState, PremiereEditPlan, PremiereEditPlanResult, PremiereTimelineCommand, ReadOptions, TargetRef, NormalizedError, VisualVerifyInput, VisualVerifyOutput, IllustratorArtboardExportResult, AfterEffectsPresetApplyResult
} from "@adobe-mcp/schemas";
import {
  AfterEffectsExpressionControl, AfterEffectsRenderAdvanced, AfterEffectsShapeCreate, AfterEffectsTextAnimate, AfterEffectsTrackingExtract,
  IllustratorImageTrace, IllustratorSwatchesCreate, IllustratorSymbolsManage, IllustratorVariableTypography, OperationsExecuteInput, OperationsExecuteResult,
  OperationsPlanInput, PhotoshopChannelMask, PhotoshopGenerativeFill, PhotoshopLayerExportAdvanced, PhotoshopLayerExportAdvancedResult, PhotoshopLayerStyle,
  PhotoshopSmartSelection, PhotoshopTransformApply, PremiereLumetriGrade, PremiereMogrtParametrize, PremiereProjectOrganize, PremiereProxiesManage, PremiereTranscriptSync,
  ToolCategory, ToolDescribeInput, ToolDescribeResult, ToolDiscoveryInput, ToolDiscoveryResult, VerificationLevel, PlanHandle
} from "@adobe-mcp/schemas";

export const Risk = z.enum(["R0", "R1", "R2", "R3", "R4"]);
export type Risk = z.infer<typeof Risk>;
type Schema = z.ZodTypeAny;
export interface ToolDefinitionBase { readonly name: string; readonly description: string; readonly risk: Risk; readonly input: Schema; readonly output: Schema; readonly mutating: boolean; readonly requiredCapabilities: readonly string[]; readonly app?: z.infer<typeof AppId>; readonly categories?: readonly z.infer<typeof ToolCategory>[]; readonly verification?: z.infer<typeof VerificationLevel>; readonly examples?: readonly Record<string, unknown>[]; readonly limitations?: readonly string[]; }
export interface ToolDefinition extends ToolDefinitionBase { readonly inputJsonSchema: Record<string, unknown>; readonly outputJsonSchema: Record<string, unknown>; }

const targetFor = (app: z.infer<typeof AppId>) => TargetRef.refine((target) => target.app === app, { message: `target.app must be ${app}` });
const readInput = (app?: z.infer<typeof AppId>) => z.object({ target: app ? targetFor(app) : TargetRef, options: ReadOptions.optional() }).strict();
const mutationInput = <T extends Schema>(app: z.infer<typeof AppId>, command: T) => z.object({ target: targetFor(app), commands: z.array(command).min(1).max(500), options: MutationOptions, plan: Plan.optional(), approval: ApprovalToken.optional(), return: z.array(z.string().min(1).max(128)).max(64).optional() }).strict();
// Every tool crosses the Gateway/Daemon boundary in this exact envelope. Tool
// metadata such as receipts and artifacts are data, never sibling fields.
const output = <T extends Schema>(data: T) => z.object({ ok: z.literal(true), data }).strict();
const errorOutput = z.object({ ok: z.literal(false), error: NormalizedError }).strict();
const unionOutput = <T extends Schema>(data: T) => output(data).or(errorOutput);
const appState = (app: z.infer<typeof AppId>) => app === "photoshop" ? PsDocumentState : app === "illustrator" ? AiDocumentState : app === "after-effects" ? AeCompState : PrSequenceState;
const emptyOutput = output(z.record(z.string(), z.unknown()));
const previewCaptureOutput = unionOutput(PreviewCaptureData);

const psContentCommand = z.discriminatedUnion("op", [
  z.object({ op: z.literal("fill"), layerId: z.string().min(1).max(256), color: z.object({ space: z.enum(["rgb", "cmyk", "lab", "gray"]), components: z.array(z.number().min(0).max(1)).min(1).max(4), alpha: z.number().min(0).max(1).default(1) }).strict() }).strict(),
  z.object({ op: z.literal("place"), layerId: z.string().min(1).max(256), artifactId: z.string().min(1).max(256) }).strict(),
  z.object({ op: z.literal("rasterize"), layerId: z.string().min(1).max(256) }).strict()
]);
const psFilterCommand = z.discriminatedUnion("op", [
  z.object({ op: z.literal("apply"), layerIds: z.array(z.string().min(1).max(256)).min(1).max(500), filter: z.enum(["blur", "sharpen", "noise", "distort"]), parameters: z.record(z.string().max(128), z.number().finite()).default({}) }).strict(),
  z.object({ op: z.literal("remove"), effectId: z.string().min(1).max(256) }).strict()
]);
const aiTextCommand = z.discriminatedUnion("op", [
  z.object({ op: z.literal("set-content"), itemId: z.string().min(1).max(256), text: z.string().max(100000) }).strict(),
  z.object({ op: z.literal("set-style"), itemId: z.string().min(1).max(256), fontFamily: z.string().max(256).optional(), fontSize: z.number().positive().max(10000).optional(), color: z.string().max(64).optional() }).strict()
]);
const aiPlaceCommand = z.object({ op: z.literal("place"), artifact: FileGrant, layerId: z.string().min(1).max(256).optional(), embedded: z.boolean().default(false) }).strict();
const aeProjectCommand = z.discriminatedUnion("op", [z.object({ op: z.literal("import"), artifactId: z.string().min(1).max(256), name: z.string().max(512) }).strict(), z.object({ op: z.literal("save-copy"), destination: FileGrant }).strict()]);
const aeQueueCommand = z.discriminatedUnion("op", [z.object({ op: z.literal("add"), compId: z.string().min(1).max(256), renderSettingsTemplate: z.string().max(256), outputModuleTemplate: z.string().max(256) }).strict(), z.object({ op: z.literal("remove"), queueItemId: z.string().min(1).max(256) }).strict()]);
const prProjectCommand = z.discriminatedUnion("op", [z.object({ op: z.literal("import"), artifactId: z.string().min(1).max(256), name: z.string().max(512) }).strict(), z.object({ op: z.literal("save-copy"), destination: FileGrant }).strict()]);
const prSequenceCommand = z.discriminatedUnion("op", [z.object({ op: z.literal("create"), name: z.string().max(512), width: z.number().int().positive(), height: z.number().int().positive(), frameRate: z.number().positive() }).strict(), z.object({ op: z.literal("delete"), sequenceId: z.string().min(1).max(256), permanent: z.literal(false).default(false) }).strict()]);
const prEffectsCommand = z.object({ op: z.literal("apply"), clipIds: z.array(z.string().min(1).max(256)).min(1).max(500), effectId: z.string().min(1).max(256), parameters: z.record(z.string().max(128), z.unknown()).default({}) }).strict();
const prMarkersCommand = z.discriminatedUnion("op", [z.object({ op: z.literal("add"), sequenceId: z.string().min(1).max(256), start: z.object({ ticks: z.string().regex(/^-?\d+$/), timebase: z.string().regex(/^[1-9]\d*$/) }).strict(), name: z.string().max(512), duration: z.object({ ticks: z.string().regex(/^-?\d+$/), timebase: z.string().regex(/^[1-9]\d*$/) }).strict(), comment: z.string().max(4096).optional() }).strict(), z.object({ op: z.literal("remove"), markerId: z.string().min(1).max(256) }).strict()]);

const definitions: ToolDefinitionBase[] = [
  { name: "adobe.system.status", description: "Estado del daemon y bridges.", risk: "R0", input: z.object({ target: TargetRef.optional(), includeBridges: z.boolean().default(true) }).strict(), output: unionOutput(z.object({ status: z.enum(["ready", "degraded", "stopped"]), bridges: z.array(z.record(z.string(), z.unknown())).max(100) }).strict()), mutating: false, requiredCapabilities: [] },
  { name: "adobe.preview.capture", description: "Captura un fotograma visual del documento, composición o timeline activo.", risk: "R0", input: PreviewCaptureInput, output: previewCaptureOutput, mutating: false, requiredCapabilities: ["state.read@1", "preview.capture@1"] },
  { name: "adobe.verify.visual", description: "Compara una captura actual con una imagen baseline.", risk: "R0", input: VisualVerifyInput, output: VisualVerifyOutput, mutating: false, requiredCapabilities: ["state.read@1", "preview.capture@1"] },
  { name: "adobe.system.capabilities", description: "Capabilities negociadas.", risk: "R0", input: z.object({ target: TargetRef.optional() }).strict(), output: unionOutput(z.object({ capabilities: z.array(z.string().regex(/^[a-z0-9.-]+@\d+$/)).max(256) }).strict()), mutating: false, requiredCapabilities: [] },
  { name: "adobe.system.activate", description: "Activa una instancia autorizada.", risk: "R1", input: z.object({ target: TargetRef, timeoutMs: z.number().int().min(1).max(30000).default(5000) }).strict(), output: unionOutput(z.object({ activated: z.boolean(), target: TargetRef }).strict()), mutating: false, requiredCapabilities: [] },
  { name: "adobe.state.inspect", description: "Inspecciona estado paginado.", risk: "R0", input: readInput(), output: unionOutput(z.record(z.string(), z.unknown())), mutating: false, requiredCapabilities: ["state.read@1"] },
  { name: "adobe.assets.grant", description: "Solicita un grant explícito.", risk: "R1", input: z.object({ access: z.enum(["read", "write", "read-write"]), suggestedName: z.string().max(255).optional(), ttlSeconds: z.number().int().min(1).max(86400).default(3600) }).strict(), output: unionOutput(FileGrant), mutating: false, requiredCapabilities: [] },
  { name: "adobe.operations.plan", description: "Planifica una operación tipada.", risk: "R0", input: z.object({ target: TargetRef, toolName: z.string().min(1).max(256), commands: z.array(z.object({ kind: z.enum(["create", "set", "transform", "delete", "export"]), entityId: z.string().min(1).max(256).optional() }).strict()).min(1).max(500), options: MutationOptions }).strict(), output: unionOutput(Plan), mutating: false, requiredCapabilities: ["state.read@1"] },
  { name: "adobe.operations.execute", description: "Ejecuta un plan previamente validado.", risk: "R2", input: z.object({ plan: Plan, approval: ApprovalToken.optional(), options: MutationOptions }).strict(), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.write@1"] },
  { name: "adobe.operations.undo", description: "Solicita una compensación segura.", risk: "R2", input: z.object({ target: TargetRef, operationId: z.string().uuid(), options: MutationOptions }).strict(), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.write@1"] },
  { name: "adobe.jobs.get", description: "Obtiene un job.", risk: "R0", input: z.object({ jobId: z.string().min(1).max(256) }).strict(), output: unionOutput(Job), mutating: false, requiredCapabilities: [] },
  { name: "adobe.jobs.cancel", description: "Cancela cooperativamente un job.", risk: "R1", input: z.object({ jobId: z.string().min(1).max(256), reason: z.string().max(1024).optional() }).strict(), output: unionOutput(Job), mutating: true, requiredCapabilities: [] },
  { name: "adobe.photoshop.inspect", description: "Inspecciona Photoshop.", risk: "R0", input: readInput("photoshop"), output: unionOutput(PsDocumentState), mutating: false, requiredCapabilities: ["state.read@1"] },
  { name: "adobe.photoshop.document", description: "Inspecciona el documento activo.", risk: "R0", input: readInput("photoshop"), output: unionOutput(PsDocumentState), mutating: false, requiredCapabilities: ["state.read@1"] },
  { name: "adobe.photoshop.layers.edit", description: "Edita capas Photoshop.", risk: "R2", input: mutationInput("photoshop", PhotoshopLayerCommand), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.photoshop.layers.content", description: "Edita contenido Photoshop.", risk: "R2", input: mutationInput("photoshop", psContentCommand), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.photoshop.filters.apply", description: "Aplica filtros allowlisted.", risk: "R3", input: mutationInput("photoshop", psFilterCommand), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.photoshop.export", description: "Exporta con grant y verificación.", risk: "R1", input: z.object({ target: targetFor("photoshop"), format: z.enum(["psd", "psb", "png", "jpeg", "tiff", "webp"]), destination: FileGrant, options: z.object({ quality: z.number().int().min(1).max(100).optional(), embedProfile: z.boolean().default(true), flatten: z.boolean().default(false), scale: z.number().positive().max(16).default(1) }).strict(), mutation: MutationOptions }).strict(), output: unionOutput(z.object({ artifact: ArtifactRef, receipt: OperationReceipt }).strict()), mutating: true, requiredCapabilities: ["state.read@1", "export.file@1"] },
  { name: "adobe.photoshop.exportLayers", description: "Exporta capas y grupos con manifest y hashes de procedencia.", risk: "R2", input: PhotoshopLayerExportSpec, output: unionOutput(PhotoshopLayerExportResult), mutating: true, requiredCapabilities: ["state.read@1", "export.file@1"] },
  { name: "adobe.illustrator.inspect", description: "Inspecciona Illustrator.", risk: "R0", input: readInput("illustrator"), output: unionOutput(AiDocumentState), mutating: false, requiredCapabilities: ["state.read@1"] },
  { name: "adobe.illustrator.document", description: "Inspecciona el documento activo.", risk: "R0", input: readInput("illustrator"), output: unionOutput(AiDocumentState), mutating: false, requiredCapabilities: ["state.read@1"] },
  { name: "adobe.illustrator.objects.edit", description: "Edita objetos Illustrator.", risk: "R2", input: mutationInput("illustrator", IllustratorEditCommand), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.illustrator.text.edit", description: "Edita texto Illustrator.", risk: "R2", input: mutationInput("illustrator", aiTextCommand), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.illustrator.assets.place", description: "Coloca un asset grantado.", risk: "R2", input: mutationInput("illustrator", aiPlaceCommand), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.illustrator.export", description: "Exporta con grant.", risk: "R1", input: z.object({ target: targetFor("illustrator"), scope: z.object({ artboardIds: z.array(z.string().min(1).max(256)).max(1000).optional(), itemIds: z.array(z.string().min(1).max(256)).max(10000).optional() }).strict(), format: z.enum(["ai", "pdf", "svg", "eps", "png", "jpeg"]), destination: FileGrant, mutation: MutationOptions }).strict(), output: unionOutput(z.object({ artifact: ArtifactRef, receipt: OperationReceipt }).strict()), mutating: true, requiredCapabilities: ["state.read@1", "export.file@1"] },
  { name: "adobe.illustrator.exportArtboards", description: "Exporta múltiples artboards a SVG o PNG con downscaling y hashes.", risk: "R2", input: IllustratorArtboardExport, output: unionOutput(IllustratorArtboardExportResult), mutating: true, requiredCapabilities: ["state.read@1", "export.file@1"] },
  { name: "adobe.aftereffects.inspect", description: "Inspecciona After Effects.", risk: "R0", input: readInput("after-effects"), output: unionOutput(AeCompState), mutating: false, requiredCapabilities: ["state.read@1"] },
  { name: "adobe.aftereffects.project", description: "Gestiona el proyecto After Effects.", risk: "R2", input: mutationInput("after-effects", aeProjectCommand), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.aftereffects.compositions.edit", description: "Edita composiciones.", risk: "R2", input: mutationInput("after-effects", AfterEffectsEditCommand), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.aftereffects.layers.edit", description: "Edita capas.", risk: "R2", input: mutationInput("after-effects", AfterEffectsEditCommand), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.aftereffects.keyframes.edit", description: "Edita keyframes.", risk: "R2", input: mutationInput("after-effects", AfterEffectsEditCommand), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.aftereffects.renderqueue.edit", description: "Edita la cola de render.", risk: "R2", input: mutationInput("after-effects", aeQueueCommand), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.aftereffects.render", description: "Renderiza con prueba de output.", risk: "R3", input: z.object({ target: targetFor("after-effects"), mode: z.enum(["queue", "aerender"]), compId: z.string().min(1).max(256), range: z.object({ start: z.object({ ticks: z.string().regex(/^-?\d+$/), timebase: z.string().regex(/^[1-9]\d*$/) }).strict(), end: z.object({ ticks: z.string().regex(/^-?\d+$/), timebase: z.string().regex(/^[1-9]\d*$/) }).strict() }).strict().optional(), renderSettingsTemplate: z.string().max(256).optional(), outputModuleTemplate: z.string().max(256).optional(), destination: FileGrant, overwrite: z.boolean().default(false), mutation: MutationOptions, plan: Plan.optional(), approval: ApprovalToken.optional() }).strict(), output: unionOutput(z.object({ artifact: ArtifactRef, receipt: OperationReceipt }).strict()), mutating: true, requiredCapabilities: ["state.read@1", "export.file@1"] },
  { name: "adobe.aftereffects.preset.apply", description: "Aplica un preset declarativo de After Effects.", risk: "R2", input: AfterEffectsPresetApply, output: unionOutput(AfterEffectsPresetApplyResult), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.premiere.inspect", description: "Inspecciona Premiere.", risk: "R0", input: readInput("premiere-pro"), output: unionOutput(PrSequenceState), mutating: false, requiredCapabilities: ["state.read@1"] },
  { name: "adobe.premiere.project.edit", description: "Edita el proyecto Premiere.", risk: "R2", input: mutationInput("premiere-pro", prProjectCommand), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.premiere.sequences.edit", description: "Edita secuencias.", risk: "R2", input: mutationInput("premiere-pro", prSequenceCommand), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.premiere.timeline.edit", description: "Edita timeline.", risk: "R2", input: mutationInput("premiere-pro", PremiereTimelineCommand), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.premiere.editPlan.execute", description: "Ejecuta un motor declarativo de edición Premiere.", risk: "R3", input: PremiereEditPlan, output: unionOutput(PremiereEditPlanResult), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1", "edit-plan.execute@1"] },
  { name: "adobe.premiere.effects.edit", description: "Edita efectos allowlisted.", risk: "R2", input: mutationInput("premiere-pro", prEffectsCommand), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.premiere.markers.edit", description: "Edita marcadores.", risk: "R1", input: mutationInput("premiere-pro", prMarkersCommand), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.premiere.export", description: "Exporta por preset.", risk: "R1", input: z.object({ target: targetFor("premiere-pro"), sequenceId: z.string().min(1).max(256), engine: z.enum(["premiere", "media-encoder"]), range: z.enum(["entire", "in-out", "work-area"]), presetId: z.string().min(1).max(256), destination: FileGrant, overwrite: z.boolean().default(false), mutation: MutationOptions }).strict(), output: unionOutput(z.object({ artifact: ArtifactRef, receipt: OperationReceipt }).strict()), mutating: true, requiredCapabilities: ["state.read@1", "export.file@1"] }
];

const advancedOutput = (schema: Schema) => output(schema);
const advancedDefinitions: ToolDefinitionBase[] = [
  { name: "adobe.tools.discover", description: "Descubre capacidades internas filtradas por aplicación, categoría, riesgo o verificación.", risk: "R0", input: ToolDiscoveryInput, output: advancedOutput(ToolDiscoveryResult), mutating: false, requiredCapabilities: [], categories: ["project"], verification: "implemented", examples: [{ app: "photoshop", category: "selection", risk: "R2" }] },
  { name: "adobe.tools.describe", description: "Devuelve JSON Schema, ejemplos, limitaciones y nivel de verificación de una herramienta.", risk: "R0", input: ToolDescribeInput, output: advancedOutput(ToolDescribeResult), mutating: false, requiredCapabilities: [], categories: ["project"], verification: "implemented" },
  { name: "adobe.operations.plan", description: "Compila una secuencia inmutable con snapshot, hash y previsualización.", risk: "R0", input: OperationsPlanInput, output: advancedOutput(PlanHandle), mutating: false, requiredCapabilities: ["state.read@1"], categories: ["project"], verification: "implemented" },
  { name: "adobe.operations.execute", description: "Ejecuta un PlanHandle tras validar revisión, hash y aprobación.", risk: "R3", input: OperationsExecuteInput, output: advancedOutput(OperationsExecuteResult), mutating: true, requiredCapabilities: ["state.write@1"], categories: ["project"], verification: "implemented" },
  { name: "adobe.photoshop.selection.smart", description: "Selección inteligente por sujeto, rango de color u objeto delimitado.", risk: "R2", input: PhotoshopSmartSelection, output: advancedOutput(z.object({ applied: z.literal(true), selectionId: z.string(), revision: z.string() }).strict()), mutating: true, requiredCapabilities: ["state.write@1", "photoshop.batchplay@1"], app: "photoshop", categories: ["selection"], verification: "experimental", limitations: ["Requiere probe de versión y host Photoshop conectado."] },
  { name: "adobe.photoshop.layer.styles", description: "Aplica estilos de capa tipados y allowlisted.", risk: "R2", input: PhotoshopLayerStyle, output: advancedOutput(z.object({ applied: z.literal(true), layerId: z.string(), style: z.string(), revision: z.string() }).strict()), mutating: true, requiredCapabilities: ["state.write@1", "photoshop.batchplay@1"], app: "photoshop", categories: ["layer", "color"], verification: "experimental" },
  { name: "adobe.photoshop.channel.mask", description: "Crea máscaras de luminosidad o desde canales alpha.", risk: "R2", input: PhotoshopChannelMask, output: advancedOutput(z.object({ applied: z.literal(true), channelId: z.string(), revision: z.string() }).strict()), mutating: true, requiredCapabilities: ["state.write@1", "photoshop.batchplay@1"], app: "photoshop", categories: ["channel", "selection"], verification: "experimental" },
  { name: "adobe.photoshop.exportLayers", description: "Aísla y exporta capas determinísticamente con artefactos content-addressed.", risk: "R3", input: PhotoshopLayerExportAdvanced.or(PhotoshopLayerExportSpec), output: advancedOutput(PhotoshopLayerExportAdvancedResult).or(unionOutput(PhotoshopLayerExportResult)), mutating: true, requiredCapabilities: ["state.read@1", "export.file@1"], app: "photoshop", categories: ["export"], verification: "implemented" },
  { name: "adobe.premiere.mogrt.parametrize", description: "Escribe parámetros validados de MOGRT mediante manifest estable.", risk: "R2", input: PremiereMogrtParametrize, output: advancedOutput(z.object({ applied: z.literal(true), updatedKeys: z.array(z.string()), revision: z.string() }).strict()), mutating: true, requiredCapabilities: ["state.write@1", "premiere.mogrt@1"], app: "premiere-pro", categories: ["typography", "media"], verification: "experimental" },
  { name: "adobe.premiere.lumetri.grade", description: "Aplica receta declarativa Lumetri, ruedas, curvas y LUT.", risk: "R2", input: PremiereLumetriGrade, output: advancedOutput(z.object({ applied: z.literal(true), clips: z.number().int().nonnegative(), revision: z.string(), manifestVersion: z.string() }).strict()), mutating: true, requiredCapabilities: ["state.write@1", "premiere.lumetri@1"], app: "premiere-pro", categories: ["color"], verification: "experimental" },
  { name: "adobe.premiere.project.organize", description: "Crea bins, importa media y aplica etiquetas de color.", risk: "R2", input: PremiereProjectOrganize, output: advancedOutput(z.object({ applied: z.literal(true), bins: z.number().int().nonnegative(), imports: z.number().int().nonnegative(), revision: z.string() }).strict()), mutating: true, requiredCapabilities: ["state.write@1", "premiere.project@1"], app: "premiere-pro", categories: ["project", "media"], verification: "experimental" },
  { name: "adobe.aftereffects.shape.create", description: "Genera formas y operadores Trim Paths, Repeater y Pucker/Bloat.", risk: "R2", input: AfterEffectsShapeCreate, output: advancedOutput(z.object({ applied: z.literal(true), groupId: z.string(), modifiers: z.array(z.string()), revision: z.string() }).strict()), mutating: true, requiredCapabilities: ["state.write@1", "aftereffects.shape@1"], app: "after-effects", categories: ["shapes"], verification: "experimental" },
  { name: "adobe.aftereffects.text.animate", description: "Crea animadores tipográficos por carácter y RangeSelector.", risk: "R2", input: AfterEffectsTextAnimate, output: advancedOutput(z.object({ applied: z.literal(true), animatorId: z.string(), revision: z.string() }).strict()), mutating: true, requiredCapabilities: ["state.write@1", "aftereffects.text@1"], app: "after-effects", categories: ["typography"], verification: "experimental" },
  { name: "adobe.aftereffects.expressionControl.add", description: "Añade controles de expresión tipados y sus vínculos.", risk: "R2", input: AfterEffectsExpressionControl, output: advancedOutput(z.object({ applied: z.literal(true), effectId: z.string(), revision: z.string() }).strict()), mutating: true, requiredCapabilities: ["state.write@1", "aftereffects.expression-control@1"], app: "after-effects", categories: ["expression"], verification: "implemented" },
  { name: "adobe.aftereffects.render", description: "Render headless con template, chunks y hash SHA-256.", risk: "R4", input: AfterEffectsRenderAdvanced, output: advancedOutput(z.object({ artifactUri: z.string().regex(/^artifact:\/\/sha256-[a-f0-9]{64}$/), sha256: z.string().regex(/^[a-f0-9]{64}$/), segments: z.number().int().positive() }).strict()), mutating: true, requiredCapabilities: ["export.file@1", "process.aerender@1"], app: "after-effects", categories: ["render", "export"], verification: "implemented" },
  { name: "adobe.illustrator.imageTrace", description: "Vectoriza imágenes con presets trazables.", risk: "R2", input: IllustratorImageTrace, output: advancedOutput(z.object({ applied: z.literal(true), paths: z.number().int().nonnegative(), revision: z.string() }).strict()), mutating: true, requiredCapabilities: ["state.write@1", "illustrator.image-trace@1"], app: "illustrator", categories: ["shapes"], verification: "experimental" },
  { name: "adobe.illustrator.swatches.create", description: "Crea muestras globales RGB/CMYK y paletas armónicas.", risk: "R1", input: IllustratorSwatchesCreate, output: advancedOutput(z.object({ applied: z.literal(true), swatchIds: z.array(z.string()), revision: z.string() }).strict()), mutating: true, requiredCapabilities: ["state.write@1", "illustrator.swatches@1"], app: "illustrator", categories: ["color"], verification: "implemented" },
  { name: "adobe.illustrator.typography.variable", description: "Ajusta ejes Weight, Width y Slant de tipografía variable.", risk: "R1", input: IllustratorVariableTypography, output: advancedOutput(z.object({ applied: z.literal(true), textItemId: z.string(), revision: z.string() }).strict()), mutating: true, requiredCapabilities: ["state.write@1", "illustrator.variable-fonts@1"], app: "illustrator", categories: ["typography"], verification: "experimental" },
  { name: "adobe.photoshop.transform.apply", description: "Aplica transformaciones libres, deformación de perspectiva o mallas de deformación.", risk: "R2", input: PhotoshopTransformApply, output: advancedOutput(z.object({ applied: z.literal(true), layerId: z.string(), revision: z.string() }).strict()), mutating: true, requiredCapabilities: ["state.write@1", "photoshop.batchplay@1"], app: "photoshop", categories: ["layer"], verification: "experimental" },
  { name: "adobe.photoshop.generative.fill", description: "Enlace experimental a Firefly Generative Fill/Expand con aprobación R3.", risk: "R3", input: PhotoshopGenerativeFill, output: advancedOutput(z.object({ applied: z.literal(true), variations: z.number().int().positive(), revision: z.string() }).strict()), mutating: true, requiredCapabilities: ["state.write@1", "experimental.firefly@1"], app: "photoshop", categories: ["layer"], verification: "experimental", limitations: ["Requiere suscripción activa y consentimiento de créditos."] },
  { name: "adobe.premiere.proxies.manage", description: "Vincula, desvincula o alterna proxys de clips en el proyecto.", risk: "R1", input: PremiereProxiesManage, output: advancedOutput(z.object({ applied: z.literal(true), updatedClips: z.number().int().nonnegative(), revision: z.string() }).strict()), mutating: true, requiredCapabilities: ["state.write@1", "premiere.proxies@1"], app: "premiere-pro", categories: ["media", "project"], verification: "experimental" },
  { name: "adobe.premiere.transcript.sync", description: "Genera y sincroniza transcripciones de voz con pistas de subtítulos.", risk: "R2", input: PremiereTranscriptSync, output: advancedOutput(z.object({ applied: z.literal(true), captionsCreated: z.boolean(), revision: z.string() }).strict()), mutating: true, requiredCapabilities: ["state.write@1", "premiere.transcript@1"], app: "premiere-pro", categories: ["media", "typography"], verification: "experimental" },
  { name: "adobe.aftereffects.tracking.extract", description: "Extrae datos de 3D Camera Tracker o Mocha AE y genera rigs.", risk: "R1", input: AfterEffectsTrackingExtract, output: advancedOutput(z.object({ applied: z.literal(true), pointsCount: z.number().int().nonnegative(), exportFormat: z.string(), revision: z.string() }).strict()), mutating: false, requiredCapabilities: ["state.read@1", "aftereffects.tracking@1"], app: "after-effects", categories: ["expression", "project"], verification: "experimental" },
  { name: "adobe.illustrator.symbols.manage", description: "Crea, inserta y gestiona símbolos vectoriales y estilos gráficos.", risk: "R2", input: IllustratorSymbolsManage, output: advancedOutput(z.object({ applied: z.literal(true), symbolId: z.string(), revision: z.string() }).strict()), mutating: true, requiredCapabilities: ["state.write@1", "illustrator.symbols@1"], app: "illustrator", categories: ["shapes", "color"], verification: "experimental" }
];

const jsonSchema = (schema: Schema): Record<string, unknown> => ({ ...(zodToJsonSchema(schema, { target: "jsonSchema2019-09" }) as Record<string, unknown>), $schema: "https://json-schema.org/draft/2020-12/schema" });
export const TOOL_CATALOG: readonly ToolDefinition[] = definitions.map((tool) => ({ ...tool, inputJsonSchema: jsonSchema(tool.input), outputJsonSchema: jsonSchema(tool.output) }));
export const ADVANCED_TOOL_CATALOG: readonly ToolDefinition[] = advancedDefinitions.map((tool) => ({ ...tool, inputJsonSchema: jsonSchema(tool.input), outputJsonSchema: jsonSchema(tool.output) }));
export const INTERNAL_TOOL_CATALOG: readonly ToolDefinition[] = [...ADVANCED_TOOL_CATALOG, ...TOOL_CATALOG.filter((legacy) => !ADVANCED_TOOL_CATALOG.some((advanced) => advanced.name === legacy.name))];
export const TOOL_NAMES = INTERNAL_TOOL_CATALOG.map((tool) => tool.name) as readonly string[];
export const PUBLIC_TOOL_CATALOG: readonly ToolDefinition[] = ["adobe.tools.discover", "adobe.tools.describe", "adobe.operations.plan", "adobe.operations.execute", "adobe.system.status", "adobe.system.capabilities", "adobe.preview.capture", "adobe.verify.visual", "adobe.jobs.get", "adobe.jobs.cancel"].map((name) => getToolFromCatalog(name));
function getToolFromCatalog(name: string): ToolDefinition { const tool = INTERNAL_TOOL_CATALOG.find((candidate) => candidate.name === name); if (!tool) throw new Error(`NOT_FOUND: tool ${name}`); return tool; }
export function getTool(name: string): ToolDefinition { return getToolFromCatalog(name); }
export function discoverTools(input: z.input<typeof ToolDiscoveryInput> = {}): readonly ToolDefinition[] { const parsed = ToolDiscoveryInput.parse(input); const query = parsed.query?.toLowerCase(); return INTERNAL_TOOL_CATALOG.filter((tool) => (parsed.app === undefined || tool.app === parsed.app) && (parsed.category === undefined || tool.categories?.includes(parsed.category)) && (parsed.risk === undefined || tool.risk === parsed.risk) && (parsed.verification === undefined || (tool.verification ?? "implemented") === parsed.verification) && (parsed.includeUnavailable || (tool.verification ?? "implemented") !== "unavailable") && (!query || `${tool.name} ${tool.description}`.toLowerCase().includes(query))).slice(0, parsed.limit); }
export function validateToolInput(name: string, input: unknown): unknown { return getTool(name).input.parse(input); }
export function validateToolOutput(name: string, input: unknown): unknown { return getTool(name).output.parse(input); }
export function riskForScope(base: Risk, entities: number, files: number, bytes: number, minutes: number): Risk { const rank: Record<Risk, number> = { R0: 0, R1: 1, R2: 2, R3: 3, R4: 4 }; let n = rank[base]; if (entities > 50 || files > 10 || bytes > 5 * 1024 ** 3 || minutes > 10) n = Math.min(4, n + 1); return `R${n}` as Risk; }
export function riskForInput(name: string, input: unknown): Risk { const base = getTool(name).risk; if (!input || typeof input !== "object") return base; const record = input as Record<string, unknown>; if (name === "adobe.photoshop.exportLayers" && "mutation" in record) return "R2"; const text = JSON.stringify(input); const rank: Record<Risk, number> = { R0: 0, R1: 1, R2: 2, R3: 3, R4: 4 }; let result = rank[base]; const declared = text.match(/"risk"\s*:\s*"(R[0-4])"/i)?.[1] as Risk | undefined; if (declared) result = Math.max(result, rank[declared]); if (/"(permanent|overwrite)"\s*:\s*true|"op"\s*:\s*"delete"/i.test(text)) result = 4; else if (/rasterize|relink|remove/i.test(text)) result = Math.max(result, 3); return `R${result}` as Risk; }
export { AppId };
