import { z } from "zod";
import { zodToJsonSchema } from "zod-to-json-schema";
import {
  AeCompState, AfterEffectsEditCommand, AfterEffectsPresetApply, AiDocumentState, ArtifactRef, AppId, ApprovalToken, FileGrant,
  IllustratorArtboardExport, IllustratorEditCommand, Job, MutationOptions, OperationReceipt, PsDocumentState, PhotoshopLayerCommand,
  PhotoshopLayerExportResult, PhotoshopLayerExportSpec, Plan, PreviewCaptureData, PreviewCaptureInput, PrSequenceState, PremiereEditPlan, PremiereEditPlanResult, PremiereTimelineCommand, ReadOptions, TargetRef, NormalizedError, VisualVerifyInput, VisualVerifyOutput, IllustratorArtboardExportResult, AfterEffectsPresetApplyResult
} from "@adobe-mcp/schemas";

export const Risk = z.enum(["R0", "R1", "R2", "R3", "R4"]);
export type Risk = z.infer<typeof Risk>;
type Schema = z.ZodTypeAny;
export interface ToolDefinitionBase { readonly name: string; readonly description: string; readonly risk: Risk; readonly input: Schema; readonly output: Schema; readonly mutating: boolean; readonly requiredCapabilities: readonly string[]; }
export interface ToolDefinition extends ToolDefinitionBase { readonly inputJsonSchema: Record<string, unknown>; readonly outputJsonSchema: Record<string, unknown>; }

const targetFor = (app: z.infer<typeof AppId>) => TargetRef.refine((target) => target.app === app, { message: `target.app must be ${app}` });
const readInput = (app?: z.infer<typeof AppId>) => z.object({ target: app ? targetFor(app) : TargetRef, options: ReadOptions.optional() }).strict();
const mutationInput = <T extends Schema>(app: z.infer<typeof AppId>, command: T) => z.object({ target: targetFor(app), commands: z.array(command).min(1).max(500), options: MutationOptions, plan: Plan.optional(), approval: ApprovalToken.optional(), return: z.array(z.string().min(1).max(128)).max(64).optional() }).strict();
// Every tool crosses the Gateway/Daemon boundary in this exact envelope. Tool
// metadata such as receipts and artifacts are data, never sibling fields.
const output = <T extends Schema>(data: T) => z.object({ ok: z.literal(true), data }).strict();
const errorOutput = z.object({ ok: z.literal(false), error: NormalizedError }).strict();
const unionOutput = <T extends Schema>(data: T) => output(data).or(errorOutput);
const appState = (app: z.infer<typeof AppId>) => app === "photoshop" ? PsDocumentState : app === "illustrator" ? AiDocumentState : app === "after-effects" ? AeCompState : PrSequenceState;
const emptyOutput = output(z.record(z.string(), z.unknown()));
const previewCaptureOutput = unionOutput(PreviewCaptureData);

const psContentCommand = z.discriminatedUnion("op", [
  z.object({ op: z.literal("fill"), layerId: z.string().min(1).max(256), color: z.object({ space: z.enum(["rgb", "cmyk", "lab", "gray"]), components: z.array(z.number().min(0).max(1)).min(1).max(4), alpha: z.number().min(0).max(1).default(1) }).strict() }).strict(),
  z.object({ op: z.literal("place"), layerId: z.string().min(1).max(256), artifactId: z.string().min(1).max(256) }).strict(),
  z.object({ op: z.literal("rasterize"), layerId: z.string().min(1).max(256) }).strict()
]);
const psFilterCommand = z.discriminatedUnion("op", [
  z.object({ op: z.literal("apply"), layerIds: z.array(z.string().min(1).max(256)).min(1).max(500), filter: z.enum(["blur", "sharpen", "noise", "distort"]), parameters: z.record(z.string().max(128), z.number().finite()).default({}) }).strict(),
  z.object({ op: z.literal("remove"), effectId: z.string().min(1).max(256) }).strict()
]);
const aiTextCommand = z.discriminatedUnion("op", [
  z.object({ op: z.literal("set-content"), itemId: z.string().min(1).max(256), text: z.string().max(100000) }).strict(),
  z.object({ op: z.literal("set-style"), itemId: z.string().min(1).max(256), fontFamily: z.string().max(256).optional(), fontSize: z.number().positive().max(10000).optional(), color: z.string().max(64).optional() }).strict()
]);
const aiPlaceCommand = z.object({ op: z.literal("place"), artifact: FileGrant, layerId: z.string().min(1).max(256).optional(), embedded: z.boolean().default(false) }).strict();
const aeProjectCommand = z.discriminatedUnion("op", [z.object({ op: z.literal("import"), artifactId: z.string().min(1).max(256), name: z.string().max(512) }).strict(), z.object({ op: z.literal("save-copy"), destination: FileGrant }).strict()]);
const aeQueueCommand = z.discriminatedUnion("op", [z.object({ op: z.literal("add"), compId: z.string().min(1).max(256), renderSettingsTemplate: z.string().max(256), outputModuleTemplate: z.string().max(256) }).strict(), z.object({ op: z.literal("remove"), queueItemId: z.string().min(1).max(256) }).strict()]);
const prProjectCommand = z.discriminatedUnion("op", [z.object({ op: z.literal("import"), artifactId: z.string().min(1).max(256), name: z.string().max(512) }).strict(), z.object({ op: z.literal("save-copy"), destination: FileGrant }).strict()]);
const prSequenceCommand = z.discriminatedUnion("op", [z.object({ op: z.literal("create"), name: z.string().max(512), width: z.number().int().positive(), height: z.number().int().positive(), frameRate: z.number().positive() }).strict(), z.object({ op: z.literal("delete"), sequenceId: z.string().min(1).max(256), permanent: z.literal(false).default(false) }).strict()]);
const prEffectsCommand = z.object({ op: z.literal("apply"), clipIds: z.array(z.string().min(1).max(256)).min(1).max(500), effectId: z.string().min(1).max(256), parameters: z.record(z.string().max(128), z.unknown()).default({}) }).strict();
const prMarkersCommand = z.discriminatedUnion("op", [z.object({ op: z.literal("add"), sequenceId: z.string().min(1).max(256), start: z.object({ ticks: z.string().regex(/^-?\d+$/), timebase: z.string().regex(/^[1-9]\d*$/) }).strict(), name: z.string().max(512), duration: z.object({ ticks: z.string().regex(/^-?\d+$/), timebase: z.string().regex(/^[1-9]\d*$/) }).strict(), comment: z.string().max(4096).optional() }).strict(), z.object({ op: z.literal("remove"), markerId: z.string().min(1).max(256) }).strict()]);

const definitions: ToolDefinitionBase[] = [
  { name: "adobe.system.status", description: "Estado del daemon y bridges.", risk: "R0", input: z.object({ target: TargetRef.optional(), includeBridges: z.boolean().default(true) }).strict(), output: unionOutput(z.object({ status: z.enum(["ready", "degraded", "stopped"]), bridges: z.array(z.record(z.string(), z.unknown())).max(100) }).strict()), mutating: false, requiredCapabilities: [] },
  { name: "adobe.preview.capture", description: "Captura un fotograma visual del documento, composición o timeline activo.", risk: "R0", input: PreviewCaptureInput, output: previewCaptureOutput, mutating: false, requiredCapabilities: ["state.read@1", "preview.capture@1"] },
  { name: "adobe.verify.visual", description: "Compara una captura actual con una imagen baseline.", risk: "R0", input: VisualVerifyInput, output: VisualVerifyOutput, mutating: false, requiredCapabilities: ["state.read@1", "preview.capture@1"] },
  { name: "adobe.system.capabilities", description: "Capabilities negociadas.", risk: "R0", input: z.object({ target: TargetRef.optional() }).strict(), output: unionOutput(z.object({ capabilities: z.array(z.string().regex(/^[a-z0-9.-]+@\d+$/)).max(256) }).strict()), mutating: false, requiredCapabilities: [] },
  { name: "adobe.system.activate", description: "Activa una instancia autorizada.", risk: "R1", input: z.object({ target: TargetRef, timeoutMs: z.number().int().min(1).max(30000).default(5000) }).strict(), output: unionOutput(z.object({ activated: z.boolean(), target: TargetRef }).strict()), mutating: false, requiredCapabilities: [] },
  { name: "adobe.state.inspect", description: "Inspecciona estado paginado.", risk: "R0", input: readInput(), output: unionOutput(z.record(z.string(), z.unknown())), mutating: false, requiredCapabilities: ["state.read@1"] },
  { name: "adobe.assets.grant", description: "Solicita un grant explícito.", risk: "R1", input: z.object({ access: z.enum(["read", "write", "read-write"]), suggestedName: z.string().max(255).optional(), ttlSeconds: z.number().int().min(1).max(86400).default(3600) }).strict(), output: unionOutput(FileGrant), mutating: false, requiredCapabilities: [] },
  { name: "adobe.operations.plan", description: "Planifica una operación tipada.", risk: "R0", input: z.object({ target: TargetRef, toolName: z.string().min(1).max(256), commands: z.array(z.object({ kind: z.enum(["create", "set", "transform", "delete", "export"]), entityId: z.string().min(1).max(256).optional() }).strict()).min(1).max(500), options: MutationOptions }).strict(), output: unionOutput(Plan), mutating: false, requiredCapabilities: ["state.read@1"] },
  { name: "adobe.operations.execute", description: "Ejecuta un plan previamente validado.", risk: "R2", input: z.object({ plan: Plan, approval: ApprovalToken.optional(), options: MutationOptions }).strict(), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.write@1"] },
  { name: "adobe.operations.undo", description: "Solicita una compensación segura.", risk: "R2", input: z.object({ target: TargetRef, operationId: z.string().uuid(), options: MutationOptions }).strict(), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.write@1"] },
  { name: "adobe.jobs.get", description: "Obtiene un job.", risk: "R0", input: z.object({ jobId: z.string().min(1).max(256) }).strict(), output: unionOutput(Job), mutating: false, requiredCapabilities: [] },
  { name: "adobe.jobs.cancel", description: "Cancela cooperativamente un job.", risk: "R1", input: z.object({ jobId: z.string().min(1).max(256), reason: z.string().max(1024).optional() }).strict(), output: unionOutput(Job), mutating: true, requiredCapabilities: [] },
  { name: "adobe.photoshop.inspect", description: "Inspecciona Photoshop.", risk: "R0", input: readInput("photoshop"), output: unionOutput(PsDocumentState), mutating: false, requiredCapabilities: ["state.read@1"] },
  { name: "adobe.photoshop.document", description: "Inspecciona el documento activo.", risk: "R0", input: readInput("photoshop"), output: unionOutput(PsDocumentState), mutating: false, requiredCapabilities: ["state.read@1"] },
  { name: "adobe.photoshop.layers.edit", description: "Edita capas Photoshop.", risk: "R2", input: mutationInput("photoshop", PhotoshopLayerCommand), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.photoshop.layers.content", description: "Edita contenido Photoshop.", risk: "R2", input: mutationInput("photoshop", psContentCommand), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.photoshop.filters.apply", description: "Aplica filtros allowlisted.", risk: "R3", input: mutationInput("photoshop", psFilterCommand), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.photoshop.export", description: "Exporta con grant y verificación.", risk: "R1", input: z.object({ target: targetFor("photoshop"), format: z.enum(["psd", "psb", "png", "jpeg", "tiff", "webp"]), destination: FileGrant, options: z.object({ quality: z.number().int().min(1).max(100).optional(), embedProfile: z.boolean().default(true), flatten: z.boolean().default(false), scale: z.number().positive().max(16).default(1) }).strict(), mutation: MutationOptions }).strict(), output: unionOutput(z.object({ artifact: ArtifactRef, receipt: OperationReceipt }).strict()), mutating: true, requiredCapabilities: ["state.read@1", "export.file@1"] },
  { name: "adobe.photoshop.exportLayers", description: "Exporta capas y grupos con manifest y hashes de procedencia.", risk: "R2", input: PhotoshopLayerExportSpec, output: unionOutput(PhotoshopLayerExportResult), mutating: true, requiredCapabilities: ["state.read@1", "export.file@1"] },
  { name: "adobe.illustrator.inspect", description: "Inspecciona Illustrator.", risk: "R0", input: readInput("illustrator"), output: unionOutput(AiDocumentState), mutating: false, requiredCapabilities: ["state.read@1"] },
  { name: "adobe.illustrator.document", description: "Inspecciona el documento activo.", risk: "R0", input: readInput("illustrator"), output: unionOutput(AiDocumentState), mutating: false, requiredCapabilities: ["state.read@1"] },
  { name: "adobe.illustrator.objects.edit", description: "Edita objetos Illustrator.", risk: "R2", input: mutationInput("illustrator", IllustratorEditCommand), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.illustrator.text.edit", description: "Edita texto Illustrator.", risk: "R2", input: mutationInput("illustrator", aiTextCommand), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.illustrator.assets.place", description: "Coloca un asset grantado.", risk: "R2", input: mutationInput("illustrator", aiPlaceCommand), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.illustrator.export", description: "Exporta con grant.", risk: "R1", input: z.object({ target: targetFor("illustrator"), scope: z.object({ artboardIds: z.array(z.string().min(1).max(256)).max(1000).optional(), itemIds: z.array(z.string().min(1).max(256)).max(10000).optional() }).strict(), format: z.enum(["ai", "pdf", "svg", "eps", "png", "jpeg"]), destination: FileGrant, mutation: MutationOptions }).strict(), output: unionOutput(z.object({ artifact: ArtifactRef, receipt: OperationReceipt }).strict()), mutating: true, requiredCapabilities: ["state.read@1", "export.file@1"] },
  { name: "adobe.illustrator.exportArtboards", description: "Exporta múltiples artboards a SVG o PNG con downscaling y hashes.", risk: "R2", input: IllustratorArtboardExport, output: unionOutput(IllustratorArtboardExportResult), mutating: true, requiredCapabilities: ["state.read@1", "export.file@1"] },
  { name: "adobe.aftereffects.inspect", description: "Inspecciona After Effects.", risk: "R0", input: readInput("after-effects"), output: unionOutput(AeCompState), mutating: false, requiredCapabilities: ["state.read@1"] },
  { name: "adobe.aftereffects.project", description: "Gestiona el proyecto After Effects.", risk: "R2", input: mutationInput("after-effects", aeProjectCommand), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.aftereffects.compositions.edit", description: "Edita composiciones.", risk: "R2", input: mutationInput("after-effects", AfterEffectsEditCommand), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.aftereffects.layers.edit", description: "Edita capas.", risk: "R2", input: mutationInput("after-effects", AfterEffectsEditCommand), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.aftereffects.keyframes.edit", description: "Edita keyframes.", risk: "R2", input: mutationInput("after-effects", AfterEffectsEditCommand), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.aftereffects.renderqueue.edit", description: "Edita la cola de render.", risk: "R2", input: mutationInput("after-effects", aeQueueCommand), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.aftereffects.render", description: "Renderiza con prueba de output.", risk: "R3", input: z.object({ target: targetFor("after-effects"), mode: z.enum(["queue", "aerender"]), compId: z.string().min(1).max(256), range: z.object({ start: z.object({ ticks: z.string().regex(/^-?\d+$/), timebase: z.string().regex(/^[1-9]\d*$/) }).strict(), end: z.object({ ticks: z.string().regex(/^-?\d+$/), timebase: z.string().regex(/^[1-9]\d*$/) }).strict() }).strict().optional(), renderSettingsTemplate: z.string().max(256).optional(), outputModuleTemplate: z.string().max(256).optional(), destination: FileGrant, overwrite: z.boolean().default(false), mutation: MutationOptions, plan: Plan.optional(), approval: ApprovalToken.optional() }).strict(), output: unionOutput(z.object({ artifact: ArtifactRef, receipt: OperationReceipt }).strict()), mutating: true, requiredCapabilities: ["state.read@1", "export.file@1"] },
  { name: "adobe.aftereffects.preset.apply", description: "Aplica un preset declarativo de After Effects.", risk: "R2", input: AfterEffectsPresetApply, output: unionOutput(AfterEffectsPresetApplyResult), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.premiere.inspect", description: "Inspecciona Premiere.", risk: "R0", input: readInput("premiere-pro"), output: unionOutput(PrSequenceState), mutating: false, requiredCapabilities: ["state.read@1"] },
  { name: "adobe.premiere.project.edit", description: "Edita el proyecto Premiere.", risk: "R2", input: mutationInput("premiere-pro", prProjectCommand), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.premiere.sequences.edit", description: "Edita secuencias.", risk: "R2", input: mutationInput("premiere-pro", prSequenceCommand), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.premiere.timeline.edit", description: "Edita timeline.", risk: "R2", input: mutationInput("premiere-pro", PremiereTimelineCommand), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.premiere.editPlan.execute", description: "Ejecuta un motor declarativo de edición Premiere.", risk: "R3", input: PremiereEditPlan, output: unionOutput(PremiereEditPlanResult), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1", "edit-plan.execute@1"] },
  { name: "adobe.premiere.effects.edit", description: "Edita efectos allowlisted.", risk: "R2", input: mutationInput("premiere-pro", prEffectsCommand), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.premiere.markers.edit", description: "Edita marcadores.", risk: "R1", input: mutationInput("premiere-pro", prMarkersCommand), output: unionOutput(OperationReceipt), mutating: true, requiredCapabilities: ["state.read@1", "state.write@1"] },
  { name: "adobe.premiere.export", description: "Exporta por preset.", risk: "R1", input: z.object({ target: targetFor("premiere-pro"), sequenceId: z.string().min(1).max(256), engine: z.enum(["premiere", "media-encoder"]), range: z.enum(["entire", "in-out", "work-area"]), presetId: z.string().min(1).max(256), destination: FileGrant, overwrite: z.boolean().default(false), mutation: MutationOptions }).strict(), output: unionOutput(z.object({ artifact: ArtifactRef, receipt: OperationReceipt }).strict()), mutating: true, requiredCapabilities: ["state.read@1", "export.file@1"] }
];

const jsonSchema = (schema: Schema): Record<string, unknown> => ({ ...(zodToJsonSchema(schema, { target: "jsonSchema2019-09" }) as Record<string, unknown>), $schema: "https://json-schema.org/draft/2020-12/schema" });
export const TOOL_CATALOG: readonly ToolDefinition[] = definitions.map((tool) => ({ ...tool, inputJsonSchema: jsonSchema(tool.input), outputJsonSchema: jsonSchema(tool.output) }));
export const TOOL_NAMES = TOOL_CATALOG.map((tool) => tool.name) as readonly string[];
export function getTool(name: string): ToolDefinition { const tool = TOOL_CATALOG.find((candidate) => candidate.name === name); if (!tool) throw new Error(`NOT_FOUND: tool ${name}`); return tool; }
export function validateToolInput(name: string, input: unknown): unknown { return getTool(name).input.parse(input); }
export function validateToolOutput(name: string, input: unknown): unknown { return getTool(name).output.parse(input); }
export function riskForScope(base: Risk, entities: number, files: number, bytes: number, minutes: number): Risk { const rank: Record<Risk, number> = { R0: 0, R1: 1, R2: 2, R3: 3, R4: 4 }; let n = rank[base]; if (entities > 50 || files > 10 || bytes > 5 * 1024 ** 3 || minutes > 10) n = Math.min(4, n + 1); return `R${n}` as Risk; }
export function riskForInput(name: string, input: unknown): Risk { const base = getTool(name).risk; if (!input || typeof input !== "object") return base; const text = JSON.stringify(input); const rank: Record<Risk, number> = { R0: 0, R1: 1, R2: 2, R3: 3, R4: 4 }; let result = rank[base]; const declared = text.match(/"risk"\s*:\s*"(R[0-4])"/i)?.[1] as Risk | undefined; if (declared) result = Math.max(result, rank[declared]); if (/"(permanent|overwrite)"\s*:\s*true|"op"\s*:\s*"delete"/i.test(text)) result = 4; else if (/rasterize|relink|remove/i.test(text)) result = Math.max(result, 3); return `R${result}` as Risk; }
export { AppId };
